#!/usr/bin/bash
# This file is in the public domain.

aur_install()
{
	cd /tmp || exit
	# Clean up possible interrupted install
	rm -Rf "$1"
	curl "https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz" | tar xz
	chown nobody "$1"
	chgrp nobody "$1"
	cd "$1" || exit

	# Get the package list
	pkglist=$(sudo -u nobody makepkg --packagelist | xargs)

	# Get the dependencies required for building that do not yet exist on the system, they will be removed after a successful build
	makedeps=$(sudo -u nobody makepkg --printsrcinfo | grep makedepends | grep -o "[a-Z0-9@._+-]*$" | xargs pacman -T | xargs)

	# Get all dependencies (build and runtime), that do not yet exist on the system
	deps=$(sudo -u nobody makepkg --printsrcinfo | grep depends | grep -o "[a-Z0-9@._+-]*$" | xargs pacman -T | xargs)
	echo "Dependencies for this package: ${deps}"

	# Install dependencies using pacman
	pacman -S --asdeps ${deps}

	# Build as nobody
	sudo -u nobody makepkg || exit

	# Install the built package
	for pkg in ${pkglist}; do
		if [ -f ${pkg}* ]; then
			pacman -U ${pkg}*
		fi
	done

	# Remove makedeps
	pacman -Rn ${makedeps}
}

usage="Usage: puckman [update,install,remove,clean,list,upgrade]\n\n\
puckman update            == pacman -Sy\n\
puckman install <package> == pacman -S <package>\n\
puckman remove  <package> == pacman -Rsc <package>\n\
puckman clean             == Remove orphan packages and cached packages that are not installed\n\
puckman upgrade           == pacman -Syu\n\
puckman list              == List explicitly installed packages"

# Determine if we need superuser privileges
if [[ $EUID -ne 0 ]]; then
	case "$1" in
		update|install|remove|clean|upgrade)
			if type -p sudo >/dev/null; then
				sudo "$0" "$@"
			else
				su root -c "$0 $*"
			fi
			exit
			;;
	esac
fi

case "$1" in
	update)
		pacman -Sy
		echo "Updating AUR package list..."
		curl https://aur.archlinux.org/packages.gz | gzip -d > /var/lib/puckman/aur_packages
		;;
	install)
		if [[ -z "$2" ]]; then
			echo -e "${usage}"
		else
			# Determine whether this package is in the AUR package list, if not assume official
			if grep -Fxq "$2" /var/lib/puckman/aur_packages 2>/dev/null; then
				aur_install "$2"
			else
				pacman -Sy "$2"
			fi
		fi
		;;
	remove)
		if [[ -z "$2" ]]; then
			echo -e "${usage}"
		else
			pacman -Rsc "$2"
		fi
		;;
	clean)
		orphans="$(pacman -Qqdt)"
		if [[ -z "${orphans}" ]]; then
			echo "No orphans to clean!"
		else
			pacman -Rsc ${orphans}
		fi
		pacman -Sc
		;;
	upgrade)
		pacman -Syu
		;;
	list)
		pacman -Qei | awk '/^Name/ { name=$3 } /^Groups/ { if ( $3 != "base" && $3 != "base-devel" ) { print name } }'
		;;
	*)
		echo -e "${usage}"
		;;

esac
